### ISSUE TITLE
中文版已知问题

### ISSUE THREAD

**Issue by SamLukeYes** [SamLukeYes/nixos-dde-iso#1]
1. 桌面启动器试图从 /usr/bin 中调用可执行程序
  - https://github.com/linuxdeepin/dde-nixos/pull/7
    - [X] ~~dde-introduction~~
    - [X] ~~dde-top-panel~~
    - [X] ~~deepin-gomoku~~
    - [X] ~~deepin-lianliankan~~
    - 以上应用已从本项目中移除
  - https://github.com/linuxdeepin/dde-nixos/pull/8
    - [X] deepin-compressor

2. 截图录屏
  - [x] 录屏功能无法使用，倒计时结束后即发生段错误退出
```log
2022-12-08, 14:32:22.874 [Debug  ] record rect: QRect(335,123 1250x750)
2022-12-08, 14:32:26.033 [Debug  ] 录屏！
2022-12-08, 14:32:26.033 [Info   ] 录屏保存目录:  "/home/nixos/视频/Screen Recordings/"
2022-12-08, 14:32:26.033 [Debug  ] m_selectedMic:  true
2022-12-08, 14:32:26.033 [Debug  ] m_selectedSystemAudio:  true
2022-12-08, 14:32:26.033 [Info   ] gstreamer lib name is  "libgstreamer-1.0.so"
fish: Job 1, 'deepin-screen-recorder' terminated by signal SIGSEGV (Address boundary error)
```

3. 控制中心
  - 个性化
    - [X] 明暗主题设置缺失
    - [X] 特效模式开关缺失
    - [X] 图标主题无可选项
    - [X] 光标主题部分缺失（只显示了 Breeze_Snow 和 breeze_cursors）
    - [ ] 字体设置缺少 fontconfig 默认的 Sans 和 Monospace 等
  - 系统信息
    - 关于本机
      - [X] 系统版本不显示
      - [X] 内存总量显示为 0B

4. 字体管理器
  - [X] 预装字体显示为用户字体

5. Calamares
  - [ ] 安装时不能选择 dde
    - 此问题预期在 dde 合入 nixpkgs 时解决，否则可能需要重写 calamares 配置
  - [ ] 不通过终端启动 calamares 时未应用 qt 主题
    - 其他非 dtk 的 qt 应用也有同样的问题
    - 将 qt5integration 加入 systemPackages 可解决该问题，但这似乎会导致图标加载不全

6. dde 组件汉化不完全
  - [ ] 相册（右键菜单）
  - [X] 字体管理器
  - [ ] 看图（右键菜单）
  - [X] 网络设置
  - [ ] 快捷键设置
  - [ ] dde-dock（右键菜单）
  - [ ] 截图录屏（任务栏图标）
  - [ ] 通知中心（任务栏图标）
  - [ ] 系统监视器（任务栏图标）

7. 窗口特效
  - [ ] 圆角不为小时，窗口移动透明特效不生效
    - 似乎在虚拟机中不会出现窗口移动透明特效的开关
  
![截图_20230111214046](https://user-images.githubusercontent.com/12882091/212058989-b4551fcd-7373-4843-8859-587735dffbcf.png)

8. 其他启动器/托盘问题
  - [X] 图标加载不全
![截图_20221213020904](https://user-images.githubusercontent.com/12882091/207311760-670ec9f8-6f75-4131-a4d3-aa38f9c2a3c2.jpg)
    - Workaround：移除部分次要应用
    - 有时部分启动器完全不出现，注销并重新登录可缓解
  - ~~deepin-clone 的启动器不显示，尽管可以通过 `gtk-launch deepin-clone` 运行~~
    - 该启动器中写了 `NoDisplay=true`，大概是预期行为而不是 bug，目前已将 deepin-clone 移除
  - [X] 特效模式下点击多任务视图无反应
  - [x] 通知中心图标缺失

（与 dde 无关的问题暂不在此记录）

**Comment by wineee** [comment]
可以直接到 dde-nixos 提 issue

**Comment by wineee** [comment]
截图录屏可以先安装个 ffmpeg

**Comment by SamLukeYes** [comment]
> 截图录屏可以先安装个 ffmpeg

确实在有 ffmpeg 的 nix shell 里运行就能录屏了，可能需要在 wrapper 里把 ffmpeg 加进 PATH

**Comment by wineee** [comment]
> 截图录屏可以先安装个 ffmpeg

按理说 ffmpeg 是可选的 ，目前的情况是 gstreamer 的后端坏了

**Comment by wineee** [comment]
多任务视图和特效模式开关修好了，我的锅，一个 dbus 服务安装位置写错了
https://github.com/linuxdeepin/dde-kwin/pull/363#event-8124427440
